# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_Defective.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 349)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_break = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_break.setGeometry(QtCore.QRect(10, 150, 300, 30))
        self.lineEdit_break.setObjectName("lineEdit_break")
        self.pushButton_cansel_pr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cansel_pr.setGeometry(QtCore.QRect(180, 280, 110, 40))
        self.pushButton_cansel_pr.setObjectName("pushButton_cansel_pr")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_name_pr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name_pr.setGeometry(QtCore.QRect(0, 70, 300, 30))
        self.lineEdit_name_pr.setObjectName("lineEdit_name_pr")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_add_pr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_pr.setGeometry(QtCore.QRect(0, 280, 100, 40))
        self.pushButton_add_pr.setObjectName("pushButton_add_pr")
        self.lineEdit_flaw = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_flaw.setGeometry(QtCore.QRect(0, 220, 310, 30))
        self.lineEdit_flaw.setObjectName("lineEdit_flaw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 340, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "имя принтера"))
        self.pushButton_cansel_pr.setText(_translate("MainWindow", "отмена"))
        self.label_3.setText(_translate("MainWindow", "поломка"))
        self.label_4.setText(_translate("MainWindow", "недостаток"))
        self.pushButton_add_pr.setText(_translate("MainWindow", "добавить "))
