# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 307)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_auth = QtWidgets.QPushButton(self.centralwidget)
        self.pb_auth.setGeometry(QtCore.QRect(20, 250, 100, 30))
        self.pb_auth.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.pb_auth.setObjectName("pb_auth")
        self.pb_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pb_exit.setGeometry(QtCore.QRect(260, 250, 90, 30))
        self.pb_exit.setStyleSheet("\n"
"background-color: rgb(85, 255, 0);")
        self.pb_exit.setObjectName("pb_exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 50, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_log = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_log.setGeometry(QtCore.QRect(50, 80, 250, 30))
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.lineEdit_psw = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_psw.setGeometry(QtCore.QRect(50, 180, 250, 30))
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 381, 41))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.pb_auth.raise_()
        self.pb_exit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_log.raise_()
        self.lineEdit_psw.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.pb_auth.setText(_translate("MainWindow", "Вход"))
        self.pb_exit.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.label_3.setText(_translate("MainWindow", "Ариант"))
