# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_working.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(471, 127)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 430, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_no_working = QtWidgets.QPushButton(Form)
        self.pushButton_no_working.setGeometry(QtCore.QRect(390, 80, 75, 23))
        self.pushButton_no_working.setObjectName("pushButton_no_working")
        self.pushButton_yes_working = QtWidgets.QPushButton(Form)
        self.pushButton_yes_working.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.pushButton_yes_working.setObjectName("pushButton_yes_working")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вы точно хотите удалить строку !"))
        self.pushButton_no_working.setText(_translate("Form", "нет"))
        self.pushButton_yes_working.setText(_translate("Form", "да "))
